# Generated by Django 2.1.7 on 2019-03-01 13:17

from django.db import migrations, models
import django.db.models.deletion
import webcomic_site.comic.models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('slug', models.CharField(blank=True, db_index=True, max_length=130, unique=True, verbose_name='Slug')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=webcomic_site.comic.models.upload_chapter_thumbnail, verbose_name='Thumbnail')),
                ('state', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published'), (9, 'Archived')], default=0, verbose_name='State')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='Publish Date')),
                ('read', models.IntegerField(default=0, verbose_name='Read')),
                ('sequence', models.IntegerField(default=1, verbose_name='Sequence')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='comic.Comic', verbose_name='Comic')),
            ],
            options={
                'db_table': 'cjwc_comic_chapter',
                'ordering': ['-sequence'],
            },
        ),
    ]
