# Generated by Django 2.1.5 on 2019-01-29 06:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32, verbose_name='Token', null=True)),
                ('is_activated', models.BooleanField(default=False, verbose_name='Is Activated')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('expire_at', models.DateTimeField(verbose_name='Expire At', null=True)),
                ('user', models.ForeignKey(on_delete='CASCADE', related_name='activations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'cjwc_user_activation',
                'ordering': ('-created_at',),
            },
        ),
    ]
