# Generated by Django 2.1.5 on 2019-02-08 13:17

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import webcomic_site.base.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('email_from', models.CharField(max_length=255, verbose_name='From')),
                ('email_to', models.TextField(verbose_name='To')),
                ('email_cc', models.TextField(blank=True, null=True, verbose_name='CC')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('body', models.TextField(verbose_name='Body')),
                ('state', models.CharField(choices=[('outgoing', 'Outgoing'), ('sent', 'Sent'), ('received', 'Received'), ('exception', 'Delivery Failed'), ('cancel', 'Cancelled')], default='outgoing', max_length=24)),
                ('send_at', models.DateTimeField(blank=True, null=True, verbose_name='Send At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete='RESTRICT', related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete='RESTRICT', related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'db_table': 'cjwc_mail',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MailAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to=webcomic_site.base.models.rename_attachment, verbose_name='Attachment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(on_delete='CASCADE', related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('mail', models.ForeignKey(on_delete='CASCADE', related_name='attachments', to='base.Mail', verbose_name='Mail Reference')),
            ],
            options={
                'db_table': 'cjwc_mail_attachment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32, null=True, verbose_name='Token')),
                ('is_activated', models.BooleanField(default=False, verbose_name='Is Activated')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('expire_at', models.DateTimeField(null=True, verbose_name='Expire At')),
                ('user', models.ForeignKey(on_delete='CASCADE', related_name='activations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'cjwc_user_activation',
                'ordering': ['-created_at'],
            },
        ),
    ]
