# Generated by Django 2.1.5 on 2019-01-30 06:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_auto_20190129_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('email_from', models.CharField(max_length=255, verbose_name='From')),
                ('email_to', models.TextField(verbose_name='To')),
                ('email_cc', models.TextField(blank=True, null=True, verbose_name='CC')),
                ('subject', models.TextField(max_length=255, verbose_name='Subject')),
                ('body', models.TextField(verbose_name='Body')),
                ('state', models.CharField(choices=[('outgoing', 'Outgoing'), ('sent', 'Sent'), ('received', 'Received'), ('exception', 'Delivery Failed'), ('cancel', 'Cancelled')], default='outgoing', max_length=24)),
                ('send_at', models.DateTimeField(blank=True, null=True, verbose_name='Send At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete='RESTRICT', related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete='RESTRICT', related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'db_table': 'cjwc_mail',
                'ordering': ('-created_at',),
            },
        ),
    ]
