# Generated by Django 2.1.5 on 2019-01-31 04:35

from django.conf import settings
from django.db import migrations, models
import webcomic_site.base.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_url', models.FileField(upload_to=webcomic_site.base.models.rename_attachment, verbose_name='Attachment')),
                ('attachment_path', models.TextField(blank=True, null=True, verbose_name='Attachment Path')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.ForeignKey(on_delete='CASCADE', related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('mail', models.ForeignKey(on_delete='CASCADE', related_name='attachments', to='base.Mail', verbose_name='Mail Reference')),
            ],
            options={
                'db_table': 'cjwc_mail_attachment',
                'ordering': ('-created_at',),
            },
        ),
    ]
