# Generated by Django 2.1.5 on 2019-01-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_mailattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailattachment',
            name='mail',
            field=models.ForeignKey(blank=True, null=True, on_delete='SET NULL', related_name='attachments', to='base.Mail', verbose_name='Mail Reference'),
        ),
    ]
